version: "2.1"
services:
  rabbitmq_server:
    container_name: rabbitmq_server
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER='${RABBITMQ_DEFAULT_USER}'
      - RABBITMQ_DEFAULT_PASS='${RABBITMQ_DEFAULT_PASS}'
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS='${RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS}'
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 7801:5672

  # workspace:
  #   build: .
  #   volumes:
  #     - ..:/workspace:cached

  rmq_producer_1:
    build:
        context: .
        dockerfile: ./Dockerfile
    container_name: rmq_producer_1
    environment:
      - PROD_NUM=1
      - HOST='${HOST}'
      - PORT='${PORT}'
      - USER='${USER}'
      - PASSWORD='${PASSWORD}'
      - REPO_URL='${REPO_URL}'
      - TOKEN='${TOKEN}'
      - URL_PATH_STORAGE='${URL_PATH_STORAGE}'
      - EXCHANGE='${EXCHANGE}'
      - EXCHANGE_TYPE='${EXCHANGE_TYPE}'
      - QUEUE_REQUEST='${QUEUE_REQUEST}'
      - QUEUE_RESPONSE='${QUEUE_RESPONSE}'
      - ROUTING_KEY_REQUEST='${ROUTING_KEY_REQUEST_PRODUCER}'
      - ROUTING_KEY_RESPONSE='${ROUTING_KEY_RESPONSE_PRODUCER}'
    depends_on:
      - rabbitmq_server
      - rmq_consumer_1
      - rmq_consumer_2

    volumes:
      - ./rabbit_producer/:/workspace/rabbit_producer_1/
    ports:
      - 7000:7000
    # command: python ./rpc_producer.py
    restart: always

  rmq_producer_2:
    build:
        context: .
        dockerfile: ./Dockerfile
    container_name: rmq_producer_2
    environment:
      - PROD_NUM=2
      - HOST='${HOST}'
      - PORT='${PORT}'
      - USER='${USER}'
      - PASSWORD='${PASSWORD}'
      - REPO_URL='${REPO_URL}'
      - TOKEN='${TOKEN}'
      - URL_PATH_STORAGE='${URL_PATH_STORAGE}'
      - EXCHANGE='${EXCHANGE}'
      - EXCHANGE_TYPE='${EXCHANGE_TYPE}'
      - QUEUE_REQUEST='${QUEUE_REQUEST}'
      - QUEUE_RESPONSE='${QUEUE_RESPONSE}'
      - ROUTING_KEY_REQUEST='${ROUTING_KEY_REQUEST_PRODUCER}'
      - ROUTING_KEY_RESPONSE='${ROUTING_KEY_RESPONSE_PRODUCER}'
    depends_on:
      - rabbitmq_server
      - rmq_consumer_1
      - rmq_consumer_2

    volumes:
      - ./rabbit_producer/:/workspace/rabbit_producer_2/
    ports:
      - 7000:7000
    # command: python ./rpc_producer.py
    restart: always

  rmq_producer_3:
    build:
        context: .
        dockerfile: ./Dockerfile
    container_name: rmq_producer_3
    environment:
      - PROD_NUM=3
      - HOST='${HOST}'
      - PORT='${PORT}'
      - USER='${USER}'
      - PASSWORD='${PASSWORD}'
      - REPO_URL='${REPO_URL}'
      - TOKEN='${TOKEN}'
      - URL_PATH_STORAGE='${URL_PATH_STORAGE}'
      - EXCHANGE='${EXCHANGE}'
      - EXCHANGE_TYPE='${EXCHANGE_TYPE}'
      - QUEUE_REQUEST='${QUEUE_REQUEST}'
      - QUEUE_RESPONSE='${QUEUE_RESPONSE}'
      - ROUTING_KEY_REQUEST='${ROUTING_KEY_REQUEST_PRODUCER}'
      - ROUTING_KEY_RESPONSE='${ROUTING_KEY_RESPONSE_PRODUCER}'
    depends_on:
      - rabbitmq_server
      - rmq_consumer_1
      - rmq_consumer_2

    volumes:
      - ./rabbit_producer/:/workspace/rabbit_producer_3/
    ports:
      - 7000:7000
    # command: python ./rpc_producer.py
    restart: always

  rmq_consumer_1:
    build:
        context: .
        dockerfile: ./Dockerfile
    container_name: rmq_consumer_1
    environment:
      - PROD_NUM=3
      - HOST='${HOST}'
      - PORT='${PORT}'
      - USER='${USER}'
      - PASSWORD='${PASSWORD}'
      - REPO_URL='${REPO_URL}'
      - TOKEN='${TOKEN}'
      - URL_PATH_STORAGE='${URL_PATH_STORAGE}'
      - EXCHANGE='${EXCHANGE}'
      - EXCHANGE_TYPE='${EXCHANGE_TYPE}'
      - QUEUE_REQUEST='${QUEUE_REQUEST}'
      - QUEUE_RESPONSE='${QUEUE_RESPONSE}'
      - ROUTING_KEY_REQUEST='${ROUTING_KEY_REQUEST_CONSUMER}'
      - ROUTING_KEY_RESPONSE='${ROUTING_KEY_RESPONSE_CONSUMER}'
    depends_on:
      - rabbitmq_server
    volumes:
      - ./rabbit_consumer/:/workspace/rabbit_consumer_1/

  rmq_consumer_2:
    build:
        context: .
        dockerfile: ./Dockerfile
    container_name: rmq_consumer_2
    environment:
      - PROD_NUM=3
      - HOST='${HOST}'
      - PORT='${PORT}'
      - USER='${USER}'
      - PASSWORD='${PASSWORD}'
      - REPO_URL='${REPO_URL}'
      - TOKEN='${TOKEN}'
      - URL_PATH_STORAGE='${URL_PATH_STORAGE}'
      - EXCHANGE='${EXCHANGE}'
      - EXCHANGE_TYPE='${EXCHANGE_TYPE}'
      - QUEUE_REQUEST='${QUEUE_REQUEST}'
      - QUEUE_RESPONSE='${QUEUE_RESPONSE}'
      - ROUTING_KEY_REQUEST='${ROUTING_KEY_REQUEST_CONSUMER}'
      - ROUTING_KEY_RESPONSE='${ROUTING_KEY_RESPONSE_CONSUMER}'
    depends_on:
      - rabbitmq_server
    volumes:
      - ./rabbit_consumer/:/workspace/rabbit_consumer_2/

    # command: python /workspace/rabbit_consumer_2/rpc_consumer.py