version: "2.1"
services:
  rabbitmq_server:
    container_name: rabbitmq_server
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 7801:5672

  # workspace:
  #   build: .
  #   volumes:
  #     - ..:/workspace:cached

  rmq_producer_1:
    build:
        context: ./rabbit_producer
        dockerfile: Dockerfile
    container_name: rmq_producer_1
    environment:
      - PROD_NUM=1
    depends_on:
      - rabbitmq_server
      - rmq_consumer_1
      - rmq_consumer_2

    volumes:
      - ./rabbit_producer/:/workspace/rabbit_producer/
    ports:
      - 7000:7000
    # command: python ./rpc_producer.py
    restart: always

  rmq_producer_2:
    build:
        context: ./rabbit_producer
        dockerfile: Dockerfile
    container_name: rmq_producer_2
    environment:
      - PROD_NUM=2
    depends_on:
      - rabbitmq_server
      - rmq_consumer_1
      - rmq_consumer_2

    volumes:
      - ./rabbit_producer/:/workspace/rabbit_producer/
    ports:
      - 7000:7000
    # command: python ./rpc_producer.py
    restart: always

  rmq_producer_3:
    build:
        context: ./rabbit_producer
        dockerfile: Dockerfile
    container_name: rmq_producer_3
    environment:
      - PROD_NUM=3
    depends_on:
      - rabbitmq_server
      - rmq_consumer_1
      - rmq_consumer_2

    volumes:
      - ./rabbit_producer/:/workspace/rabbit_producer/
    ports:
      - 7000:7000
    # command: python ./rpc_producer.py
    restart: always

  rmq_consumer_1:
    build:
        context: ./rabbit_consumer
        dockerfile: Dockerfile
    container_name: rmq_consumer_1
    depends_on:
      - rabbitmq_server

  rmq_consumer_2:
    build:
        context: ./rabbit_consumer
        dockerfile: Dockerfile
    container_name: rmq_consumer_2
    depends_on:
      - rabbitmq_server

    # command: python ./rpc_consumer.py